version: '3.8'

services:
  book-service-postgres:
    image: 'postgres:16'
    container_name: 'book-service-postgres'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
