server:
  port: 8080
spring:
  mvc:
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5433}/postgres?TimeZone=UTC
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        transaction:
        #          isolation: 2
        #        flushMode: SERIALIZABLE
        jdbc:
          time_zone: UTC
          format_sql: true
  flyway:
    enabled: true
    locations: classpath:migration
    baselineOnMigrate: true
    validateOnMigrate: true
    validateMigrationNaming: true
logging:
  level:
    org:
      springframework:
        security: INFO
    #    org.springframework.transaction: TRACE
    root: INFO
    com:
      service_book:
        demo: INFO
