spring:
  mvc:
    async:
      request-timeout: 60000
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5433}/postgres?TimeZone=UTC
  flyway:
    enabled: true
    locations: classpath:migration
    baselineOnMigrate: true
    validateOnMigrate: true
    validateMigrationNaming: true
